config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
  root 'pages#home'
  get  'pages/home'
  get  'privacypolicy' => 'pages#privacypolicy'
  get  'cancelpolicy' => 'pages#cancelpolicy'
  get  'about' => 'pages#about'
  get  'join' => 'pages#join'
  get  'my_cancelpolicy' => 'pages#my_cancelpolicy'

  resources :users,     only:     [:show, :index]
  resources :services
  resources :openings do
    resources :exceptions, module: :openings
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end
  resources :messages, only:      [:new, :create]

  resources :services do
    resources :bookings, only:    [:new, :create]
  end

  resources :bookings, only:      [:edit, :update, :destroy]

  resources :services do
    resources :reviews, only:     [:create, :destroy]
  end

  get 'your_sessions' => 'bookings#your_sessions'
  get 'your_bookings' => 'bookings#your_bookings'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_many :reviews

  validates :user_id, :title, :category, presence: true
  validates :title, length: { maximum: 50 }
  validates :content, length: {minimum: 10, maximum: 600 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :user_authorization, except: [:show, :index, :new, :create]

  # Set_service before any other call in edit, update and destroy.
  before_action :set_service, only: [:edit, :update, :destroy]

  def index
    @services = current_user.services
  end

  def show
    @user = User.find(params[:id])
    @services = @user.services
  end

  def new
    @service = Service.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @service = current_user.services.build(service_params)
    @service.price = params[:service][:price].gsub(/\D/, '').to_i
    @service.category_id = params[:category_id]

    if @service.save
      flash[:success] = "Service created!"
      redirect_to services_path
    else
      @categories = Category.all.map{|c| [ c.name, c.id ] }
      render :new
    end
  end

  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def update
    if @service.update_attributes(service_params)
      flash[:success] = "Service updated!"
      redirect_to services_path
     else
       @categories = Category.all.map{|c| [ c.name, c.id ] }
       render :edit
     end
    @service.category_id = params[:category_id]
  end

  def destroy
    @service.destroy
    flash[:success] = "Service deleted"
    redirect_to services_path
  end

  private

    def service_params
      params.require(:service).permit(:content, :title, :price, :category_id)
    end

    def user_authorization
     redirect_to(root_url) unless current_user.id == Service.find(params[:id]).user_id
    end

    def set_service
      @service = Service.find(params[:id])
    end
end

app/helpers/services_helper.rb
module ServicesHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/services/_calendar.html.erb
<div id="openings_calendar-<%= service.id.to_s %>">
  <%= month_calendar events: openings, params: { service: service } do |day, openings| %>
    <div>
      <strong><%= day.to_s(:short) %></strong>
    </div>
    <% openings.each do |opening| %>
      <div>
        <%= link_to opening.start_time.strftime("%H:%M"), new_service_booking_url(start_time: opening.start_time, opening_id: opening.id, service_id: service) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <%= render 'shared/error_messages', object: @service %>

    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, size: "50x1", :maxlength => 50 %><br />

    <%= f.label :content %>
    <%= f.text_area :content, size: "50x7", :maxlength => 600 %><br />

    <%= f.label :price %>
    <b>€</b><%= f.text_field :price %><br /><br / />

    <%= select_tag(:category_id, options_for_select(@categories), :prompt => 'Please select category') %><br /><br />

  <%= f.submit class: "btn btn-complete" %>

<% end %>
</br >
<%= link_to "Back", services_path %>

app/views/services/_new_service_form.html.erb
<h3>Awesome! Next up, please add your first service</h3>
<p>You will be able to add more later.</p>

<%= form_for(service) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true, size: "50x1", :maxlength => 50 %><br />

  <%= f.label :content %>
  <%= f.text_area :content, size: "50x7", :maxlength => 600 %><br />

  <%= f.label :price %>
  <b>€</b><%= f.text_field :price %><br/><br //>

  <%= select_tag(:category_id, options_for_select(categories), :prompt => 'Please select category') %><br/>
  <br>

  <%= f.submit "Create service", class: "btn btn-complete" %>

<% end %>

app/views/services/_service.html.erb
<style type="text/css">
  .simple-calendar {
    font-size: 10px;
  }

  .simple-calendar .calendar-heading {
    font-size: 24px;
  }
</style>

<% @services.order("id desc").each do |service| %>
  <div class="p-t-50">
    <dl>
      <dt class="block-title p-b-15 text-black">
        <%= image_tag('fallback/massage.jpg', size: "100x85") %>
        <%= service.title %>
        <button class="btn btn-lg btn-rounded btn-white btn-animated from-top fa fa-heart" data-toggle="modal" data-target="#bookingsModal<%= service.id%>">
          <span>Book</span>
        </button>

        <!-- BOOK MODAL (STICK UP)  -->
        <div class="modal fade center" id="bookingsModal<%= service.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header clearfix text-left">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <i class="pg-close fs-21"></i>
                        </button>
                        <% if user_signed_in? %>
                          <h4>Book <%= service.title %></h4>
                        <% else %>
                          <h5>Please log in first</h5>
                        <% end %>
                    </div>
                    <div class="modal-body">
                      <% if user_signed_in? %>
                          <% if flash[:error].present? %>
                            <div id="error_explanation">
                              <p><%= flash[:error] %></p>
                            </div>
                          <% end %>
                          <div class="row">
                            <div class="col-sm-12">
                                <%= hidden_field_tag "recipients", @user.id %>
                                <div class="form-group">
                                  <%= label_tag 'Available times' %>
                                  <%= render partial: 'services/calendar', locals: { openings: @calendar_openings, service: service } %>
                                </div>
                            </div>
                          </div>
                      <% else %>
                        <%= render "users/sessions/form", :action => "new_user_session_path", :layout=> false %>
                      <% end %>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- END BOOK MODAL (STICK UP)  -->
          <br />
      </dt>
      <dd class="m-b-30"><%= service.content %></dd>
    </dl>
  </div>
<% end %>

app/views/services/cancelpolicy.html.erb
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <%# if current_user.cancel_policy.exists? %>
      <div class="form-group form-group-default">
        <div class="">
          <%# flash.each do |key, value| %>
            <!-- <div class="alert alert-<%= key %> bg-<%= key %>-light"><%= value %></div> -->
          <%# end %>
        </div>
      </div>
      <%# else %>
        <div class="form-group form-group-default">

            <h3>
              Hi <%= current_user.first_name %>, to become a provider at Enlive we need to learn a little more about you.
            </h3>

            <%= render 'users/registrations/cancel_policy_form', :action => "edit_user_registration_path", :layout=> false %>

        <%# end %><br/><br/>
      </div>
    </div>
  </section>

app/views/services/edit.html.erb
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group form-group-default">
        <h2>Edit service</h2>
          <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/services/index.html.erb
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <% if current_user.services.exists? %>
      <div class="form-group form-group-default">
        <div class="">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %> bg-<%= key %>-light"><%= value %></div>
          <% end %>
        </div>
        <% if current_user.uid.present? %>
          <% if current_user.openings.exists? %>
            <% provide(:title, 'My Services') %>
            <h1>My Services <%= link_to "My Openings", openings_path, class: "btn btn-lg btn-complete btn-bordered pull-right" %>
            </h1>
            Cancel policy: <%= link_to current_user.cancel_policy, my_cancelpolicy_path %>
            <hr />
            <ul class="services">
              <% @services.each do |service| %>
                <li>
                  <%= service.title %> (<%= service.category.name %>):
                  <%= service.content %><br/>
                  Price: $<%= service.price %>
                  |
                  <%= link_to "Edit", edit_service_path(service) %>
                  |
                  <%= link_to "Delete", service, method: :delete, data: { confirm: "You sure?" } %>
                </li>
              <% end %>
            </ul>
            <hr />
            <%= link_to "New service", new_service_path, class: "btn btn-complete btn-bordered" %>


          <% else %>

          <!-- Step 4 -->

            <% controller.redirect_to openings_path, alert: "Last and final step. Please let people know when you are available." %>
          <% end %>
      </div>
        <% else %>

          <!-- Step 3 -->

          <h3>Almost done! Please let us know how to pay you by clicking the button below</h3>
          <p>
            You will get redirected to Stripe, world-renowned business payments company that will handle your payments information.
          </p>
          <br />

            <%= link_to "Enter my payout details", user_stripe_connect_omniauth_authorize_path, class: "btn btn-complete btn-lg btn-large btn-block" %>
        <% end %>

      <% else %>
        <div class="form-group form-group-default">
          <% if current_user.avatar.present? && current_user.description.present? %>

          <!-- Step 2 -->

            <%= render partial: "services/new_service_form", locals: {service: Service.new, categories: Category.all.map{|c| [ c.name, c.id ] }} %>

          <% else %>

          <!-- Step 1 -->

            <%= render '/services/onboarding/1' %>

          <% end %>
        <% end %><br/><br/>
      </div>
    </div>
  </section>

app/views/services/new.html.erb
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group form-group-default">
        <h2>Start providing</h2>
          <%= render 'form' %>
      </div>
    </div>
  </div>
</section>