config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
  root 'pages#home'
  get  'pages/home'
  get  'privacypolicy' => 'pages#privacypolicy'
  get  'cancelpolicy' => 'pages#cancelpolicy'
  get  'about' => 'pages#about'
  get  'join' => 'pages#join'
  get  'my_cancelpolicy' => 'pages#my_cancelpolicy'

  resources :users,     only:     [:show, :index]
  resources :services
  resources :openings do
    resources :exceptions, module: :openings
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end
  resources :messages, only:      [:new, :create]

  resources :services do
    resources :bookings, only:    [:new, :create]
  end

  resources :bookings, only:      [:edit, :update, :destroy]

  resources :services do
    resources :reviews, only:     [:create, :destroy]
  end

  get 'your_sessions' => 'bookings#your_sessions'
  get 'your_bookings' => 'bookings#your_bookings'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]

  def index
    @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  private

    def get_mailbox
      @mailbox ||= current_user.mailbox
    end

    def get_conversation
      @conversation ||= @mailbox.conversations.find(params[:id])
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
  <p><%= render 'conversations/participants', conversation: conversation %></p>

    <p><%= conversation.last_message.body %>
      <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= avatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group form-group-default">
        <!-- <% page_header "Your Conversations" %> -->
        <h1>Your messages</h1></br >

        <!-- <p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-complete' %></p> -->

        <ul class="list-group">
          <%= render partial: 'conversations/conversation', collection: @conversations %>
        </ul>

        <%= will_paginate %>
      </div>
    </div>
  </div>
</section>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>
<section class="bg-master-lightest p-b-65 p-t-100">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group form-group-default">
        <p>Chatting with
          <%= render 'conversations/participants', conversation: @conversation %>
        </p>

        <div class="panel panel-default">
          <div class="panel-heading"><%= @conversation.subject %></div>

          <div class="panel-body">
            <div class="messages">
              <% @conversation.receipts_for(current_user).each do |receipt| %>
                <div class="media">
                  <% message = receipt.message %>
                  <div class="media-left">
                    <%= avatar_for message.sender, message.sender.first_name %>
                  </div>

                  <div class="media-body">
                    <h6 class="media-heading"><%= message.sender.first_name %>
                      says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
                    <%= message.body %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <%= form_tag reply_conversation_path(@conversation), method: :post do %>
          <div class="form-group">
            <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
          </div>
          <%= submit_tag "Send Message", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</section>