config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
  root 'pages#home'
  get  'pages/home'
  get  'privacypolicy' => 'pages#privacypolicy'
  get  'cancelpolicy' => 'pages#cancelpolicy'
  get  'about' => 'pages#about'
  get  'join' => 'pages#join'
  get  'my_cancelpolicy' => 'pages#my_cancelpolicy'

  resources :users,     only:     [:show, :index]
  resources :services
  resources :openings do
    resources :exceptions, module: :openings
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end
  resources :messages, only:      [:new, :create]

  resources :services do
    resources :bookings, only:    [:new, :create]
  end

  resources :bookings, only:      [:edit, :update, :destroy]

  resources :services do
    resources :reviews, only:     [:create, :destroy]
  end

  get 'your_sessions' => 'bookings#your_sessions'
  get 'your_bookings' => 'bookings#your_bookings'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :services, dependent: :destroy
  has_many :bookings
  has_many :reviews
  has_many :openings, dependent: :destroy
  has_one :location, dependent: :destroy

  accepts_nested_attributes_for :services, :location

  scope :bodyworker,  ->{ joins(:services).where("category_id = ?", 1) }
  scope :shaman,      ->{ joins(:services).where("category_id = ?", 2) }
  scope :healer,      ->{ joins(:services).where("category_id = ?", 3) }
  scope :teacher,     ->{ joins(:services).where("category_id = ?", 4) }


  def service_categories(user)
    categories = ""
    user.services.map(&:category).uniq.each do |service|
      categories << service.name
      categories << ", " unless service == user.services.map(&:category).uniq.last
    end
    categories
  end

  acts_as_messageable
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

 # User Avatar Validation
 validates_integrity_of  :avatar
 validates_processing_of :avatar

 CANCEL_POLICY_OPTIONS = [
   'Flexible',
   'Moderate',
   'Strict'
 ]

  def mailboxer_email(object)
    email
  end

  def avg_rating
    avg_rating = []
    services.each do |service|
      service.reviews.each do |review|
        avg_rating.push review.star
      end
    end
    return avg_rating.sum.to_f / avg_rating.size
  end

  def received_reviews
    reviews = []
    services.each do |s|
      reviews.push s.reviews.count
    end
    return reviews.sum
  end

  def active_provider?
    services.present? && uid.present? && openings.present?
  end

  private
    def avatar_size_validation
     errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    signed_in_root_path(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

    if @user.services.exists?
      @services = @user.services

      @userList = User.find(params[:id])
      @servicesList = @userList.services

      @openings = @user.openings
      @calendar_openings = @openings.flat_map{ |e| e.calendar_openings(params.fetch(:start_date, Time.zone.now).to_date) }
    end

    @servicecalendar = Service.find(params[:service]) unless params[:service].nil?
  end

  def index
    scope = params[:users]

    scope.nil? ? @users = User.all : @users = User.joins(:services).where("category_id = ?", scope).distinct
  end

  private

    def service_params
      params.require(:service).permit(:content, :title, :price)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def service_categories(user)
    categories = ""
    user.services.map(&:category).uniq.each do |service|
      categories << service.name
      categories << ", " unless service == user.services.map(&:category).uniq.last
    end
    categories
  end

end

app/views/users/_browse.html.erb
<div class="container">
  <div class="row row-same-height">
    <% users.shuffle.each do |user| %>
      <% if user.active_provider? %>
        <div class="col-sm-3">
          <div class="matched-outer b-black b-a text-center b-rad-md no-overflow m-b-20">
            <div class="matched-inner-top bg-master-lighter p-t-10 p-b-0">
              <%= link_to image_tag(user.avatar.thumb, size: "100x100", class: "img-circle", :style => "border: 3px solid #fff"), user %>
              <h3 class="font-montserrat no-margin"><%= truncate (user.first_name + ' ' + user.last_name), length: 20 %></h1>
              <p class="no-margin fs-20"><span id="average_rating_<%= user.first_name %>"></p>
              <p class="no-margin fs-12"><%= pluralize(user.received_reviews, 'review') %></span></p>
            </div>
            <div class="matched-inner-bot p-t-0 p-b-20">
              <ul class="list-unstyled p-l-30 p-r-30  sm-p-l-10 sm-p-r-10 hint-text m-t-20">
                <li class="b-b b-grey">
                  <p class="font-arial fs-14 no-margin p-t-5 p-b-5">
                    <strong><%= service_categories(user) %></strong>
                  </p>
                </li>
                <li class="b-b b-grey">
                  <p class="font-arial fs-14 no-margin p-t-5 p-b-5">Located in <%= user.location.try(:city) %></p>
                </li>
                <!-- <li class="b-b b-grey"> -->
                  <!-- <p class="font-arial fs-14 no-margin p-t-5 p-b-5">Verified account</p> -->
                <!-- </li> -->
              </ul>
            </div>
            <div class="p-t-5 p-b-20">
              <%= link_to "Read more", user, class: "btn btn-rounded btn-white" %>
            </div>
          </div>
        </div>
        <script>
        $('#average_rating_<%= user.first_name %>').raty({
          readOnly: true,
          score: <%= user.avg_rating %>
        });
        </script>
        <script>
          $(function() {
              $('.matched-outer').matchHeight({ property: 'min-height' });
              $('.matched-inner-top').matchHeight({ property: 'min-height' });
              $('.matched-inner-bot').matchHeight({ property: 'min-height' });
          });
        </script>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!-- BEGIN HERO WITH PARALLAX -->
<section class="demo-hero-45" data-pages="parallax">
  <div class="inner full-height">
    <!-- BEGIN SLIDER -->
    <div class="swiper-container" id="hero">
      <div class="swiper-wrapper">
        <!-- BEGIN SLIDE -->
        <div class="swiper-slide fit">
          <!-- BEGIN IMAGE PARRALAX -->
          <div class="slider-wrapper">
            <div class="image" data-swiper-parallax="30%">
              <%= lazy_image_tag('holding_girl2.jpg', placeholder: 'holding_girl2_low.jpg', class: "image-responsive-height", style: "position: relative; top: -0px;") %>
            </div>
          </div>
          <!-- END IMAGE PARRALAX -->
          <!-- BEGIN CONTENT -->
          <div class="content-layer">
            <div class="inner full-height">
              <div class="container-xs-height full-height">
                <div class="col-xs-height col-middle text-left">
                  <div class="container">
                    <div class="col-md-6 no-padding col-xs-10 col-xs-offset-1">
                      <h1 class="text-white sm-text-center" data-swiper-parallax="-15%">You're in good hands with us</h1>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SLIDE -->
      </div>
    </div>
  </div>
  <!-- END SLIDER -->
</section>
<!-- BEGIN BROWSE SECTION -->
<section class="p-b-40 p-t-40">
  <div class="container">
    <div class="m-b-30">
      <h1 class="text-center ">Our amazing experts</h1>
      <div class="b-b b-grey m-t-30"></div>
      <div class="col-md-9 col-md-offset-3 col-sm-8 col-sm-offset-2 p-t-15 p-b-15">
        <ul class="no-style no-margin">
          <li class="m-r-20 m-l-20 inline sm-block text-center sm-p-b-5 sm-m-b-5 b-grey sm-b-b">
            <%= link_to "Bodyworkers", users_path(users: '1'), :class => 'link active text-black fs-13 block-title', :remote => true %>
          </li>
          <li class="m-r-20 m-l-20 inline sm-block text-center sm-p-b-5 sm-m-b-5 b-grey sm-b-b">
            <%= link_to "Shamans", users_path(users: '2'), :class => 'link active text-black fs-13 block-title', :remote => true %>
          </li>
          <li class="m-r-20 m-l-20 inline sm-block text-center sm-p-b-5 sm-m-b-5 b-grey sm-b-b">
            <%= link_to "Healers", users_path(users: '3'), :class => 'link active text-black fs-13 block-title', :remote => true %>
          </li>
          <li class="m-r-20 m-l-20 inline sm-block text-center sm-p-b-5 sm-m-b-5 b-grey sm-b-b">
            <%= link_to "Teachers", users_path(users: '4'), :class => 'link active text-black fs-13 block-title', :remote => true %>
          </li>
          <li class="m-r-20 m-l-20 inline sm-block text-center ">
            <!-- <a href="#" class="link active text-black fs-13 block-title">More</a> -->
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<section class="bg-master-lightest p-b-65 p-t-5">
  <div id="showcase">
    <%#= render 'browse', locals: {users: @users}) %>
    <%= render partial: 'users/browse', locals: { users: @users } %>
  </div>
</section>

app/views/users/index.js.erb
// inside increase_count.js.erb

// Fetch the link in question and re-render it
// The newly rendered link will use the updated value from the instance variable within the #increase_count action

// Generates the link
// Use the j helper to escape any JavaScript within the text

var link = "<%= j render(partial: "users/browse", locals: {users: @users}) %>";
// Select the link using jQuery and update it
$("#showcase").html(link);

app/views/users/show.html.erb
<style>
.wrapper {
  overflow:hidden;
}

.wrapper div {
}
#one {
  float:left;
  width:140px;
}
#two {
  overflow:hidden;
}

@media screen and (max-width: 1200px) {
   #one {
    float: none;
    margin-right:0;
    width:auto;
    border:0;
    margin-left: auto;
    margin-right: auto
  }

    #two {
      margin-top: -20px;
      margin-bottom: -20px;
    }
}
</style>


<!-- BEGIN USER SECTION -->
<section class="p-b-65 p-t-100">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="row">
          <div class="col-sm-5 sm-m-t-30">
            <div class="p-r-65 md-p-l-0 md-p-r-10 sm-m-t-20">
              <div class="b-black b-a text-center b-rad-md no-overflow">
                <div class="wrapper bg-master-lighter">
                  <div id="one">
                    <%= image_tag(@user.avatar.thumb, size: "145x145", class: "img-circle m-t-15", :style => "border: 3px solid #fff") %>
                  </div>
                  <div class="bg-master-lighter p-t-30 p-b-30">
                    <div id="two">
                      <h5 class="no-margin">Hi, I'm</h5>
                      <h1 class="font-montserrat no-margin"><%= @user.first_name %></h1>
                      <p class="no-margin fs-14"><span id="average_rating"></span></p>
                      <p class="no-margin fs-14"><%= pluralize(@user.received_reviews, 'review') %></span></p>
                    </div>
                  </div>
                </div>
                <div class="p-t-30 p-b-20">
                  <div class="p-l-15 p-r-15">
                    <p class="semi-bold"> <%= @user.description %> </p>
                  </div>
                  <ul class="list-unstyled p-l-60 p-r-60  sm-p-l-10 sm-p-r-10 hint-text m-t-20">
                    <li class="b-b b-grey">
                      <p class="font-arial fs-14 no-margin p-t-5 p-b-5">Located in <%= @user.location.city %></p>
                    </li>
                    <!-- <li class="b-b b-grey">
                      <p class="font-arial fs-14 no-margin p-t-5 p-b-5">Facebook verified</p>
                    </li>
                    <li class="b-b b-grey">
                      <p class="font-arial fs-14  no-margin p-t-5 p-b-5">Passport verified</p>
                    </li> -->
                  </ul>
                </div>
                <div class="bg-master-lighter p-t-20 p-b-20">
                  <button class="btn btn-lg btn-rounded btn-white btn-animated from-top pg pg-mail" data-toggle="modal" data-target="#messageModal">
                    <span>Contact</span>
                  </button>
                  <script>
                  $('#average_rating').raty({
                    readOnly: true,
                    score: <%= @user.avg_rating %>
                  });
                  </script>
                  <!-- CONTACT MODAL (STICK UP)  -->
                  <div class="modal fade stick-up" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                          <div class="modal-content">
                              <div class="modal-header clearfix text-left">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                  <i class="pg-close fs-14"></i>
                                  </button>
                                  <% if user_signed_in? %>
                                    <h5>Contact <%= @user.first_name %></h5>
                                  <% else %>
                                    <h5>Please log in first</h5>
                                  <% end %>
                              </div>
                              <div class="modal-body">
                                <% if user_signed_in? %>
                                  <% if flash[:error].present? %>
                                    <div id="error_explanation">
                                      <p><%= flash[:error] %></p>
                                    </div>
                                  <% end %>
                                  <%= form_tag messages_path, method: :post do %>
                                    <div class="row">
                                      <div class="col-sm-12">
                                          <%= hidden_field_tag "recipients", @user.id %>
                                          <div class="form-group">
                                            <%= label_tag 'message[subject]', 'Subject' %>
                                            <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
                                          </div>
                                          <div class="form-group">
                                            <%= label_tag 'message[body]', 'Message' %>
                                            <%= text_area_tag 'message[body]', nil, rows: 5, class: 'form-control', required: true %>
                                          </div>
                                          <%= submit_tag 'Send', class: 'btn btn-complete btn-lg btn-large btn-block' %>
                                      </div>
                                    </div>
                                  <% end %>
                                <% else %>
                                  <%= render "users/sessions/form", :action => "new_user_session_path", :layout=> false %>
                                <% end %>
                              </div>
                          </div>
                          <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
                  </div>
                  <!-- END CONTACT MODAL (STICK UP)  -->
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-7  sm-p-t-20 ">
            <div class="">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %> bg-<%= key %>-light"><%= value %></div>
              <% end %>
            </div>
            <% if @user.services.any? %>
              <h1 class="m-t-30 light">What I can offer you.</h1>
                <%= render 'services/service' %>
            <% end %>
            <h1 class="m-t-30 light">Reviews</h1>
            <% if user_signed_in? %>
              <div>
                <%= render 'reviews/form' %>
              </div>
            <% end %>
            <div>
              <%= render 'reviews/list' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- END USER SECTION -->

app/views/users/show.js.erb
$("#openings_calendar-<%= j @servicecalendar.id.to_s %>").html("<%= j render(partial: "services/calendar", locals: {openings: @calendar_openings, service: @servicecalendar}) %>");